### ISSUE TITLE
Capture navigations that redirect

### ISSUE THREAD

**Issue by g-ortuno** [raymeskhoury/sw-launch#2]
The explainer touches on events triggered by redirects [[1]](https://github.com/raymeskhoury/sw-launch/blob/master/explainer.md#handling-redirects-which-trigger-launch-events). Should we also mention the inverse i.e. sites capturing a navigation that immediately redirects? I think sometimes this happens when the user isn't signed in yet.

**Comment by raymeskhoury** [comment]
Do you have an example?

**Comment by g-ortuno** [comment]
This was happening with Google sites that required login. For example if a user was not signed in and had `https://chat.google.com/`, we would capture the navigation, open the app, and then immediately get redirected to accounts.google.com.

Now that I think about it, I don't think this is a problem now that we have CCT. Previously this was a problem because the out-of-scope navigations bounced back to the browser. So I don't think we need to mention this.
